const __DEMO__ = false;
    const __SUPERVISOR__ = true;
    const __BUILD__ = "latest"

import { O as createCommonjsModule, P as unwrapExports, aH as lib$1 } from './auth-dev.js';
import { eu as tslib_es6 } from './main-dev.js';
import { l as lib } from './index-dev.js';
import './stop_propagation-dev.js';
import 'lit-html/is-server.js';

var InitializePluralRules_1=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.InitializePluralRules=void 0;function InitializePluralRules(pl,locales,options,_a){var availableLocales=_a.availableLocales,relevantExtensionKeys=_a.relevantExtensionKeys,localeData=_a.localeData,getDefaultLocale=_a.getDefaultLocale,getInternalSlots=_a.getInternalSlots;var requestedLocales=(0, lib.CanonicalizeLocaleList)(locales);var opt=Object.create(null);var opts=(0, lib.CoerceOptionsToObject)(options);var internalSlots=getInternalSlots(pl);internalSlots.initializedPluralRules=true;var matcher=(0, lib.GetOption)(opts,'localeMatcher','string',['best fit','lookup'],'best fit');opt.localeMatcher=matcher;internalSlots.type=(0, lib.GetOption)(opts,'type','string',['cardinal','ordinal'],'cardinal');(0, lib.SetNumberFormatDigitOptions)(internalSlots,opts,0,3,'standard');var r=(0, lib$1.ResolveLocale)(availableLocales,requestedLocales,opt,relevantExtensionKeys,localeData,getDefaultLocale);internalSlots.locale=r.locale;return pl;}exports.InitializePluralRules=InitializePluralRules;});unwrapExports(InitializePluralRules_1);InitializePluralRules_1.InitializePluralRules;

var GetOperands_1=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.GetOperands=void 0;/**
 * http://ecma-international.org/ecma-402/7.0/index.html#sec-getoperands
 * @param s
 */function GetOperands(s){(0, lib.invariant)(typeof s==='string',"GetOperands should have been called with a string");var n=(0, lib.ToNumber)(s);(0, lib.invariant)(isFinite(n),'n should be finite');var dp=s.indexOf('.');var iv;var f;var v;var fv='';if(dp===-1){iv=n;f=0;v=0;}else {iv=s.slice(0,dp);fv=s.slice(dp,s.length);f=(0, lib.ToNumber)(fv);v=fv.length;}var i=Math.abs((0, lib.ToNumber)(iv));var w;var t;if(f!==0){var ft=fv.replace(/0+$/,'');w=ft.length;t=(0, lib.ToNumber)(ft);}else {w=0;t=0;}return {Number:n,IntegerDigits:i,NumberOfFractionDigits:v,NumberOfFractionDigitsWithoutTrailing:w,FractionDigits:f,FractionDigitsWithoutTrailing:t};}exports.GetOperands=GetOperands;});unwrapExports(GetOperands_1);GetOperands_1.GetOperands;

var ResolvePlural_1=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.ResolvePlural=void 0;/**
 * http://ecma-international.org/ecma-402/7.0/index.html#sec-resolveplural
 * @param pl
 * @param n
 * @param PluralRuleSelect Has to pass in bc it's implementation-specific
 */function ResolvePlural(pl,n,_a){var getInternalSlots=_a.getInternalSlots,PluralRuleSelect=_a.PluralRuleSelect;var internalSlots=getInternalSlots(pl);(0, lib.invariant)((0, lib.Type)(internalSlots)==='Object','pl has to be an object');(0, lib.invariant)('initializedPluralRules'in internalSlots,'pluralrules must be initialized');(0, lib.invariant)((0, lib.Type)(n)==='Number','n must be a number');if(!isFinite(n)){return 'other';}var locale=internalSlots.locale,type=internalSlots.type;var res=(0, lib.FormatNumericToString)(internalSlots,n);var s=res.formattedString;var operands=(0, GetOperands_1.GetOperands)(s);return PluralRuleSelect(locale,type,n,operands);}exports.ResolvePlural=ResolvePlural;});unwrapExports(ResolvePlural_1);ResolvePlural_1.ResolvePlural;

var get_internal_slots=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});var internalSlotMap=new WeakMap();function getInternalSlots(x){var internalSlots=internalSlotMap.get(x);if(!internalSlots){internalSlots=Object.create(null);internalSlotMap.set(x,internalSlots);}return internalSlots;}exports.default=getInternalSlots;});unwrapExports(get_internal_slots);

var intlPluralrules=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.PluralRules=void 0;var get_internal_slots_1=(0, tslib_es6.__importDefault)(get_internal_slots);function validateInstance(instance,method){if(!(instance instanceof PluralRules)){throw new TypeError("Method Intl.PluralRules.prototype.".concat(method," called on incompatible receiver ").concat(String(instance)));}}/**
 * http://ecma-international.org/ecma-402/7.0/index.html#sec-pluralruleselect
 * @param locale
 * @param type
 * @param _n
 * @param param3
 */function PluralRuleSelect(locale,type,_n,_a){var IntegerDigits=_a.IntegerDigits,NumberOfFractionDigits=_a.NumberOfFractionDigits,FractionDigits=_a.FractionDigits;return PluralRules.localeData[locale].fn(NumberOfFractionDigits?"".concat(IntegerDigits,".").concat(FractionDigits):IntegerDigits,type==='ordinal');}var PluralRules=/** @class */function(){function PluralRules(locales,options){// test262/test/intl402/RelativeTimeFormat/constructor/constructor/newtarget-undefined.js
// Cannot use `new.target` bc of IE11 & TS transpiles it to something else
var newTarget=this&&this instanceof PluralRules?this.constructor:void 0;if(!newTarget){throw new TypeError("Intl.PluralRules must be called with 'new'");}return (0, InitializePluralRules_1.InitializePluralRules)(this,locales,options,{availableLocales:PluralRules.availableLocales,relevantExtensionKeys:PluralRules.relevantExtensionKeys,localeData:PluralRules.localeData,getDefaultLocale:PluralRules.getDefaultLocale,getInternalSlots:get_internal_slots_1.default});}PluralRules.prototype.resolvedOptions=function(){validateInstance(this,'resolvedOptions');var opts=Object.create(null);var internalSlots=(0, get_internal_slots_1.default)(this);opts.locale=internalSlots.locale;opts.type=internalSlots.type;['minimumIntegerDigits','minimumFractionDigits','maximumFractionDigits','minimumSignificantDigits','maximumSignificantDigits'].forEach(function(field){var val=internalSlots[field];if(val!==undefined){opts[field]=val;}});opts.pluralCategories=(0, tslib_es6.__spreadArray)([],PluralRules.localeData[opts.locale].categories[opts.type],true);return opts;};PluralRules.prototype.select=function(val){var pr=this;validateInstance(pr,'select');var n=(0, lib.ToNumber)(val);return (0, ResolvePlural_1.ResolvePlural)(pr,n,{getInternalSlots:get_internal_slots_1.default,PluralRuleSelect:PluralRuleSelect});};PluralRules.prototype.toString=function(){return '[object Intl.PluralRules]';};PluralRules.supportedLocalesOf=function(locales,options){return (0, lib.SupportedLocales)(PluralRules.availableLocales,(0, lib.CanonicalizeLocaleList)(locales),options);};PluralRules.__addLocaleData=function(){var data=[];for(var _i=0;_i<arguments.length;_i++){data[_i]=arguments[_i];}for(var _a=0,data_1=data;_a<data_1.length;_a++){var _b=data_1[_a],d=_b.data,locale=_b.locale;PluralRules.localeData[locale]=d;PluralRules.availableLocales.add(locale);if(!PluralRules.__defaultLocale){PluralRules.__defaultLocale=locale;}}};PluralRules.getDefaultLocale=function(){return PluralRules.__defaultLocale;};PluralRules.localeData={};PluralRules.availableLocales=new Set();PluralRules.__defaultLocale='';PluralRules.relevantExtensionKeys=[];PluralRules.polyfilled=true;return PluralRules;}();exports.PluralRules=PluralRules;try{// IE11 does not have Symbol
if(typeof Symbol!=='undefined'){Object.defineProperty(PluralRules.prototype,Symbol.toStringTag,{value:'Intl.PluralRules',writable:false,enumerable:false,configurable:true});}try{// https://github.com/tc39/test262/blob/master/test/intl402/PluralRules/length.js
Object.defineProperty(PluralRules,'length',{value:0,writable:false,enumerable:false,configurable:true});}catch(error){// IE 11 sets Function.prototype.length to be non-configurable which will cause the
// above Object.defineProperty to throw an error.
}// https://github.com/tc39/test262/blob/master/test/intl402/RelativeTimeFormat/constructor/length.js
Object.defineProperty(PluralRules.prototype.constructor,'length',{value:0,writable:false,enumerable:false,configurable:true});// https://github.com/tc39/test262/blob/master/test/intl402/RelativeTimeFormat/constructor/supportedLocalesOf/length.js
Object.defineProperty(PluralRules.supportedLocalesOf,'length',{value:1,writable:false,enumerable:false,configurable:true});}catch(ex){// Meta fixes for test262
}});unwrapExports(intlPluralrules);intlPluralrules.PluralRules;

var supportedLocales=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.supportedLocales=void 0;// This file is generated from supported-locales-gen.ts
exports.supportedLocales=["af","ak","am","an","ar","ars","as","asa","ast","az","bal","be","bem","bez","bg","bho","bm","bn","bo","br","brx","bs","ca","ce","ceb","cgg","chr","ckb","cs","cy","da","de","doi","dsb","dv","dz","ee","el","en","eo","es","et","eu","fa","ff","fi","fil","fo","fr","fur","fy","ga","gd","gl","gsw","gu","guw","gv","ha","haw","he","hi","hnj","hr","hsb","hu","hy","ia","id","ig","ii","io","is","it","iu","ja","jbo","jgo","jmc","jv","jw","ka","kab","kaj","kcg","kde","kea","kk","kkj","kl","km","kn","ko","ks","ksb","ksh","ku","kw","ky","lag","lb","lg","lij","lkt","ln","lo","lt","lv","mas","mg","mgo","mk","ml","mn","mo","mr","ms","mt","my","nah","naq","nb","nd","ne","nl","nn","nnh","no","nqo","nr","nso","ny","nyn","om","or","os","osa","pa","pap","pcm","pl","prg","ps","pt-PT","pt","rm","ro","rof","ru","rwk","sah","saq","sat","sc","scn","sd","sdh","se","seh","ses","sg","sh","shi","si","sk","sl","sma","smi","smj","smn","sms","sn","so","sq","sr","ss","ssy","st","su","sv","sw","syr","ta","te","teo","th","ti","tig","tk","tl","tn","to","tpi","tr","ts","tzm","ug","uk","und","ur","uz","ve","vi","vo","vun","wa","wae","wo","xh","xog","yi","yo","yue","zh","zu"];});unwrapExports(supportedLocales);supportedLocales.supportedLocales;

var shouldPolyfill_1=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});exports.shouldPolyfill=void 0;function supportedLocalesOf(locale){if(!locale){return true;}var locales=Array.isArray(locale)?locale:[locale];return Intl.PluralRules.supportedLocalesOf(locales).length===locales.length;}function shouldPolyfill(locale){if(locale===void 0){locale='en';}if(!('PluralRules'in Intl)||new Intl.PluralRules('en',{minimumFractionDigits:2}).select(1)==='one'||!supportedLocalesOf(locale)){return locale?(0, lib$1.match)([locale],supportedLocales.supportedLocales,'en'):undefined;}}exports.shouldPolyfill=shouldPolyfill;});unwrapExports(shouldPolyfill_1);shouldPolyfill_1.shouldPolyfill;

var polyfill=createCommonjsModule(function(module,exports){Object.defineProperty(exports,"__esModule",{value:true});if((0, shouldPolyfill_1.shouldPolyfill)()){Object.defineProperty(Intl,'PluralRules',{value:intlPluralrules.PluralRules,writable:true,enumerable:false,configurable:true});}});var polyfill$1 = unwrapExports(polyfill);

export { polyfill as __moduleExports, polyfill$1 as default };
