export const languages = {
  en: {
    'common.add_camera': 'Add Camera',
    'common.back': 'Back',
    'common.camera': 'camera',
    'common.confirm': 'confirm',
    'common.custom_camera': 'Custom Camera',
    'common.delete': 'Delete',
    'common.delete_camera': 'Delete Camera',
    'common.edit': 'Edit',
    'common.edit_camera': 'Edit Camera',
    'common.go_back': 'Back',
    'dialog_text.verify_action': 'This action can not be undone',
    'form.add_multi_channels': 'Add all channels?',
    'form.advanced_options': 'Advanced Options',
    'form.authentication': 'Select Authetication',
    'form.channel': 'Channel',
    'form.framerate': 'Framerate',
    'form.integration': 'Select type of Integration',
    'form.ip': 'IP',
    'form.issues.duplicated_camera_name': 'There is already a camera with that name',
    'form.issues.ip_missing': 'No IP address provided',
    'form.issues.missing_integration': 'Select an integration type',
    'form.issues.n_cameras': 'Number of cameras is not valid',
    'form.issues.name': 'Camera name is required',
    'form.issues.static_stream_source_missing': 'No static or stream URL',
    'form.name': 'Camera Name (Obligatory)',
    'form.number_of_cameras': 'Number of cameras',
    'form.password': 'Password',
    'form.record_video_of_camera': 'Record Video of Camera',
    'form.rtsp_transport': 'Select RTSP Transport',
    'form.still_image_url': 'Static Image URL',
    'form.still_url_door': 'Still Image Door',
    'form.stream_source': 'Stream URL',
    'form.stream_source_door': 'Stream Door',
    'form.username': 'Username',
    'form.verify_ssl': 'Verify SSL',
    'search.brands': 'Search Brands',
    'search.cameras': 'Search cameras',
    'search.models': 'Search Models',
  },
  pt: {
    'common.back': 'Voltar',
    'common.camera': 'Camera',
    'common.delete': 'Apagar',
    'common.edit': 'Editar',
  },
};
